export const ADD_INGREDIENT = 'ADD_INGREDIENT';
export const REMOVE_INGREDIENT = 'REMOVE_INGREDIENT';
export const INIT_INGRIDIENTS = 'INIT_INGRIDIENTS';
export const INIT_INGRIDIENTS_FAIL = 'INIT_INGRIDIENTS_FAIL';

export const BURGER_ORDER_SUCCESS = 'BURGER_ORDER_SUCCESS';
export const BURGER_ORDER_FAIL = 'BURGER_ORDER_FAIL';
export const BURGER_ORDER_LOAD = 'BURGER_ORDER_LOAD';
export const BURGER_ORDER_INIT = 'BURGER_ORDER_INIT';
export const REDIRECT_CHANGE = 'REDIRECT_CHANGE';

export const FETCH_ORDERS_SUCCESS = 'FETCH_ORDERS_SUCCESS';
export const FETCH_ORDERS_FAIL = 'FETCH_ORDERS_FAIL';
export const FETCH_ORDERS_LOAD = 'FETCH_ORDERS_LOAD';

export const LOGIN_START = "LOGIN_START";
export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_FAIL = "LOGIN_FAIL";
export const LOGIN_LOGOUT = "LOGIN_LOGOUT";